-- TIPOS PERSONALIZADOS

-- TIPO ENUM PARA STATUS_PEDIDO
CREATE TYPE STATUS_PEDIDO_ENUM AS ENUM (
    'EM ANDAMENTO',
    'EM PREPARO',
    'SAIU PARA ENTREGA',
    'ENTREGUE',
    'CANCELADO'
);

-- TIPO ENUM PARA A UNIDADE DE MEDIDA DO INGREDIENTE
CREATE TYPE UNIDADE_MEDIDA_ENUM AS ENUM (
    'UNIDADE',
    'KG',
    'G',
    'L',
    'ML',
    'M',
    'CM'
);

-- TIPO ENUM PARA O STATUS DE COMPRA DE INGREDIENTES
CREATE TYPE STATUS_COMPRA_ENUM AS ENUM (
    'PENDENTE',
    'EM ANDAMENTO',
    'FINALIZADA',
    'CANCELADA'
);


