-- CRIAÇÃO DAS TABELAS DO BANCO DE DADOS

-- TABELA CLIENTE
CREATE TABLE CLIENTE (
	COD_CLIENTE SERIAL PRIMARY KEY,
	NOME VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(10),
	TELEFONE VARCHAR(11),
	ATIVO BOOLEAN DEFAULT TRUE
);

-- TABELA DE ENDEREÇOS
CREATE TABLE ENDERECO (
	COD_ENDERECO SERIAL PRIMARY KEY,
	COMPLEMENTO VARCHAR(255),
	NUMERO VARCHAR(10),
	BAIRRO VARCHAR(100),
	RUA VARCHAR(100),
	CEP VARCHAR(10)
);

-- TABELA ASSOCIATIVA ENTRE CLIENTE E ENDEREÇO
CREATE TABLE CLIENTE_ENDERECO (
	COD_CLIENTE INT NOT NULL,
	COD_ENDERECO INT NOT NULL,
	PRIMARY KEY (COD_CLIENTE, COD_ENDERECO),
	FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
	FOREIGN KEY (COD_ENDERECO) REFERENCES ENDERECO(COD_ENDERECO)
);

-- TABELA DE ATENDENTE
CREATE TABLE ATENDENTE (
	COD_ATENDENTE SERIAL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	EMAIL VARCHAR(255),
	ATIVO BOOLEAN DEFAULT TRUE
);

-- TABELA DE ENTREGADOR
CREATE TABLE ENTREGADOR (
	COD_ENTREGADOR SERIAL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
	ATIVO BOOLEAN DEFAULT TRUE
);

-- TABELA DOS TIPOS DE PAGAMENTOS
CREATE TABLE TIPO_PAGAMENTO (
	COD_TIPO_PAGAMENTO SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);


-- TABELA PEDIDO
CREATE TABLE PEDIDO (
	COD_PEDIDO SERIAL PRIMARY KEY,
	COD_CLIENTE INT NOT NULL,
	COD_ENDERECO INT NOT NULL,
	COD_ATENDENTE INT REFERENCES ATENDENTE(COD_ATENDENTE),
	COD_ENTREGADOR INT REFERENCES ENTREGADOR(COD_ENTREGADOR),
	DATA_HORA_PEDIDO TIMESTAMP NOT NULL,
	HORA_PREVISTA_ENTREGA TIMESTAMP NOT NULL,
	HORA_ENTREGA_REAL TIMESTAMP NOT NULL,
	STATUS STATUS_PEDIDO_ENUM NOT NULL,
	OBSERVACAO VARCHAR(255),
	VALOR_TOTAL NUMERIC(10, 2),
	FOREIGN KEY (COD_CLIENTE, COD_ENDERECO) REFERENCES CLIENTE_ENDERECO(COD_CLIENTE, COD_ENDERECO)
);

-- TABELA DO PRODUTO (OS DOCES)
CREATE TABLE PRODUTO (
	COD_PRODUTO SERIAL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	DESCRICAO TEXT,
	VALOR_UNITARIO NUMERIC(10, 2)
);

-- TABELA ASSOCIATIVA ENTRE PEDIDO E PRODUTO
CREATE TABLE ITEM_PEDIDO (
	COD_PEDIDO INT REFERENCES PEDIDO(COD_PEDIDO),
	COD_PRODUTO INT REFERENCES PRODUTO(COD_PRODUTO),
	QUANTIDADE INT NOT NULL,
	PRIMARY KEY(COD_PEDIDO, COD_PRODUTO)
);


-- TABELA DE INGREDIENTES
CREATE TABLE INGREDIENTE (
	COD_INGREDIENTE SERIAL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	UNIDADE_MEDIDA UNIDADE_MEDIDA_ENUM NOT NULL,
	QTD_ESTOQUE NUMERIC(10, 2)
);

-- TABELA ASSOCIATIVA ENTRE PRODUTO E INGREDIENTE (É A RECEITA)
CREATE TABLE PRODUTO_INGREDIENTE (
	 COD_PRODUTO INT REFERENCES PRODUTO(COD_PRODUTO),
	 COD_INGREDIENTE INT REFERENCES INGREDIENTE(COD_INGREDIENTE),
	 QTD_UTILIZADA NUMERIC(10, 2) NOT NULL,
	 PRIMARY KEY(COD_PRODUTO, COD_INGREDIENTE)
);

-- TABELA DE FORNECEDOR
CREATE TABLE FORNECEDOR (
	COD_FORNECEDOR SERIAL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
	ATIVO BOOLEAN DEFAULT TRUE
);

-- TABELA COMPRA (COMPRA DE INGREDIENTES COM UM DETERMINADO FORNECEDOR)
CREATE TABLE COMPRA (
	COD_COMPRA SERIAL PRIMARY KEY,
	COD_FORNECEDOR INT REFERENCES FORNECEDOR(COD_FORNECEDOR),
	DATA_COMPRA TIMESTAMP NOT NULL,
	VALOR_TOTAL NUMERIC(10, 2),
	STATUS STATUS_COMPRA_ENUM NOT NULL
);

-- TABELA ASSOCIATIVA ENTRE COMPRA E INGREDIENTE (ITEM_COMPRA)
CREATE TABLE ITEM_COMPRA (
	COD_COMPRA INT REFERENCES COMPRA(COD_COMPRA),
	COD_INGREDIENTE INT REFERENCES INGREDIENTE(COD_INGREDIENTE),
	VALOR_UNITARIO NUMERIC(10, 2) NOT NULL,
	QUANTIDADE INT NOT NULL,
	PRIMARY KEY(COD_COMPRA, COD_INGREDIENTE)
);


































